export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  amazonAccessKeyId: process.env.AMAZON_ACCESS_KEY_ID ?? "",
  amazonSecretKey: process.env.AMAZON_SECRET_KEY ?? "",
  amazonAssociateId: process.env.AMAZON_ASSOCIATE_ID ?? "homestore0ba-20",
  pinterestAccessToken: process.env.PINTEREST_ACCESS_TOKEN ?? "",
  pinterestAccountId: process.env.PINTEREST_ACCOUNT_ID ?? "homestore0315",
  automationScheduleCron: process.env.AUTOMATION_SCHEDULE_CRON ?? "0 9 * * *",
};
